title: John Doe # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Engineering in Physics Student (December 2023) @ Tecnológico de Monterrey in Mexico
  Lawyer (December 2022) @ Tecnológico de Monterrey
  Former Data Engineer Intern @ Meta (Facebook) (Summer 2022, Menlo Park, California)
  <br><br>
  Interested in Legal Tech, Data Engineering, Data Science, Machine Learning, NLP 
  <br><br>
  <a href="www.linkedin.com/in/alejandrosdl">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
